import type { ProcessTemplate } from "./types";

export const TEMPLATES: ProcessTemplate[] = [
  {
    id: "banking",
    name: "Banking operations",
    operator: "Ops analyst / banker",
    industry: "Banking",
    promise:
      "Exceptions from core banking, wires, and KYC land as one queue: who, why, what to do before the window closes.",
    adapter: {
      id: "core-banking",
      name: "Core + payments + CRM",
      system: "FIS / Jack Henry / Salesforce",
      plug: "Read holds, KYC timers, and relationship value. No write-back until the bank signs off.",
    },
    rankingLabel: "exposure × time-sensitivity × customer impact × confidence",
    rankingInputs: [
      { key: "exposure", label: "Exposure", weight: 0.32, hint: "Dollars or franchise risk if this sits." },
      { key: "urgency", label: "Time sensitivity", weight: 0.28, hint: "SLA, cutoff, or customer waiting." },
      { key: "customer", label: "Customer impact", weight: 0.22, hint: "Value and relationship fragility." },
      { key: "confidence", label: "Confidence", weight: 0.18, hint: "How sure the source system is." },
    ],
    fields: [
      { key: "product", label: "Product", type: "badge", inQueue: true, inCase: true },
      { key: "amount", label: "Amount", type: "money", inQueue: true, inCase: true },
      { key: "sla", label: "Window", type: "hours", inQueue: true, inCase: true },
      { key: "segment", label: "Segment", type: "text", inQueue: true, inCase: true },
      { key: "source", label: "Source system", type: "text", inQueue: false, inCase: true },
    ],
    dispositions: [
      { key: "act", label: "Resolve now", description: "Clear the exception inside policy. Clock stops." },
      { key: "monitor", label: "Park with owner", description: "Still ours. Assign and keep in the queue." },
      { key: "dismiss", label: "Not an exception", description: "Misrouted or already handled. Remove from today." },
    ],
    cases: [
      {
        id: "bnk-wire-ofac",
        templateId: "banking",
        title: "Outgoing wire held on OFAC near-match",
        subject: "Northbridge Logistics · $482,000",
        whyFlagged: "Name similarity 0.81 against an SDN alias. Wire cutoff in 3 hours. Commercial relationship is 11 years, no prior hits.",
        recommendedAction: "Open the hit, compare full legal name and address, release if the match fails the second identifier. Do not auto-release.",
        uncertainty: "The screening engine does not see the DBA on the invoice. A human has to look at both strings.",
        evidence: [
          { label: "Screening", detail: "OFAC fuzzy match 0.81 — threshold 0.75" },
          { label: "Core", detail: "Same beneficiary paid 14 times in 18 months, never held" },
          { label: "CRM", detail: "Relationship manager: payroll + trade lane, no disputes" },
        ],
        scores: { exposure: 0.88, urgency: 0.94, customer: 0.8, confidence: 0.46 },
        values: { product: "Wire", amount: 482000, sla: 3, segment: "Commercial", source: "Payments hub" },
        recencyHours: 1,
      },
      {
        id: "bnk-kyc-refresh",
        templateId: "banking",
        title: "KYC refresh overdue — commercial credit",
        subject: "Helios Foods · $12.4M exposure",
        whyFlagged: "Periodic refresh due 11 days ago. Credit line is live. Last beneficial-owner file is 38 months old.",
        recommendedAction: "Freeze new originations only. Keep existing draws. Send the RM a 5-day evidence request.",
        uncertainty: "Ownership may have changed after a 2025 recap. Core does not know. CRM notes are informal.",
        evidence: [
          { label: "KYC timer", detail: "Cycle overdue 11 days" },
          { label: "Credit", detail: "Outstanding $8.1M of $12.4M" },
          { label: "Docs", detail: "Last CIP packet 2023-06" },
        ],
        scores: { exposure: 0.84, urgency: 0.7, customer: 0.86, confidence: 0.9 },
        values: { product: "Credit", amount: 12400000, sla: 120, segment: "Commercial", source: "KYC warehouse" },
        recencyHours: 18,
      },
      {
        id: "bnk-ach-returns",
        templateId: "banking",
        title: "ACH return rate jumped on a merchant",
        subject: "BrightPath Fitness · 6.8% returns",
        whyFlagged: "Return rate moved from 1.1% to 6.8% in 9 days. NACHA warning territory. Same MID, new campaign.",
        recommendedAction: "Throttle origination to yesterday's volume. Call merchant ops. Do not kill the MID overnight.",
        uncertainty: "Could be a billing error in their new app, not fraud. Need 20 return codes before we know.",
        evidence: [
          { label: "ACH ops", detail: "R10/R07 mix, not R05" },
          { label: "Volume", detail: "$1.9M originated last 7 days" },
          { label: "History", detail: "Clean for 22 months" },
        ],
        scores: { exposure: 0.62, urgency: 0.78, customer: 0.55, confidence: 0.74 },
        values: { product: "ACH", amount: 1900000, sla: 24, segment: "SMB", source: "ACH ops" },
        recencyHours: 6,
      },
      {
        id: "bnk-duplicate-ach",
        templateId: "banking",
        title: "Possible duplicate vendor payment",
        subject: "AP run · $67,440 twice",
        whyFlagged: "Same amount, same vendor ABA, 14 minutes apart. File came from two ERP exports after a failed batch.",
        recommendedAction: "Hold the second item. Confirm with AP. Release only with a unique invoice id.",
        uncertainty: "Could be two legitimate invoices that happen to match. The ERP sometimes strips invoice numbers.",
        evidence: [
          { label: "Payments", detail: "Exact amount + ABA match" },
          { label: "ERP", detail: "Batch 4482 failed, then rerun" },
          { label: "Vendor", detail: "No dispute history" },
        ],
        scores: { exposure: 0.4, urgency: 0.66, customer: 0.35, confidence: 0.58 },
        values: { product: "ACH", amount: 67440, sla: 8, segment: "Corporate AP", source: "Core" },
        recencyHours: 4,
      },
      {
        id: "bnk-limit-request",
        templateId: "banking",
        title: "Limit increase sits outside policy band",
        subject: "Maya Chen · card limit $8k → $25k",
        whyFlagged: "Customer requested 3× limit. Score is fine. Policy cap for this segment is 2× without a second look.",
        recommendedAction: "Offer $16k now, queue underwriting for the rest. Do not decline cold.",
        uncertainty: "Income on file is 16 months old. If payroll is higher, the full amount is fine.",
        evidence: [
          { label: "Policy", detail: "Segment cap 2× without review" },
          { label: "Bureau", detail: "Score 742, utilization 19%" },
          { label: "App", detail: "Customer in-session, waiting" },
        ],
        scores: { exposure: 0.28, urgency: 0.82, customer: 0.6, confidence: 0.8 },
        values: { product: "Card", amount: 25000, sla: 2, segment: "Consumer", source: "Originations" },
        recencyHours: 0.5,
      },
      {
        id: "bnk-payroll-fail",
        templateId: "banking",
        title: "Payroll standing order failed",
        subject: "River Clinic · 214 employees",
        whyFlagged: "Insufficient collected funds 40 minutes before ACH window. This clinic has failed once before, on a holiday.",
        recommendedAction: "Call the office manager. Offer same-day wire path. Do not let payroll miss.",
        uncertainty: "Could be a delayed insurance receivable, not a going-concern issue.",
        evidence: [
          { label: "Core", detail: "Collected balance $41k short" },
          { label: "Calendar", detail: "Pay date Friday" },
          { label: "CRM", detail: "Prior miss Dec 2025, recovered same day" },
        ],
        scores: { exposure: 0.7, urgency: 0.96, customer: 0.88, confidence: 0.92 },
        values: { product: "ACH", amount: 486000, sla: 1, segment: "Commercial", source: "Core" },
        recencyHours: 0.7,
      },
      {
        id: "bnk-dormant",
        templateId: "banking",
        title: "Dormant deposit, sudden outgoing activity",
        subject: "Estate of J. Hale · $210,000",
        whyFlagged: "No customer-initiated activity for 19 months, then two external transfers totaling $91k this morning.",
        recommendedAction: "Hold remaining outgoing. Verify the executor packet before anything else leaves.",
        uncertainty: "Could be a legitimate estate settlement. Could be an account takeover on a quiet book.",
        evidence: [
          { label: "Core", detail: "Dormant flag set 2025-01" },
          { label: "Channel", detail: "New device, first login in 19 months" },
          { label: "Docs", detail: "Executor letter imaged last week" },
        ],
        scores: { exposure: 0.75, urgency: 0.88, customer: 0.5, confidence: 0.5 },
        values: { product: "Deposits", amount: 210000, sla: 4, segment: "Trust", source: "Core + digital" },
        recencyHours: 2,
      },
      {
        id: "bnk-nsf-pattern",
        templateId: "banking",
        title: "NSF fees stacking on a hardship account",
        subject: "Luis Ortega · 7 NSF in 11 days",
        whyFlagged: "Hardship tag is on. Fees are still posting. This is a complaint and UDAAP waiting to happen.",
        recommendedAction: "Stop incremental fees. Reverse the last cycle. Route to hardship desk, not collections.",
        uncertainty: "Tag may be stale. Confirm the program is still active before waiving the full stack.",
        evidence: [
          { label: "Core", detail: "7 NSF posts since Aug 3" },
          { label: "Flags", detail: "Hardship = true, expiry blank" },
          { label: "Complaints", detail: "None yet" },
        ],
        scores: { exposure: 0.45, urgency: 0.6, customer: 0.7, confidence: 0.77 },
        values: { product: "Deposits", amount: 840, sla: 24, segment: "Consumer", source: "Core" },
        recencyHours: 9,
      },
    ],
  },
  {
    id: "regulatory",
    name: "Regulatory analyst",
    operator: "GRC / regulatory analyst",
    industry: "Enterprise GRC",
    promise:
      "New rules, control breaks, and exam asks become a ranked obligation queue — mapped the way a GRC team already works in OpenPages.",
    adapter: {
      id: "openpages",
      name: "IBM OpenPages + regulator feeds",
      system: "IBM OpenPages / GRC",
      plug: "Obligations, controls, and issues stay in OpenPages. Desk ranks what the analyst opens today.",
    },
    rankingLabel: "harm × applicability × deadline pressure × evidence gap",
    rankingInputs: [
      { key: "harm", label: "Harm if missed", weight: 0.3, hint: "Customer, capital, or exam damage." },
      { key: "applicability", label: "Applicability", weight: 0.28, hint: "Is this actually our citation?" },
      { key: "deadline", label: "Deadline pressure", weight: 0.24, hint: "Effective date, comment period, exam." },
      { key: "gap", label: "Evidence gap", weight: 0.18, hint: "Missing or stale proof." },
    ],
    fields: [
      { key: "citation", label: "Citation", type: "text", inQueue: true, inCase: true },
      { key: "owner", label: "Owner", type: "text", inQueue: true, inCase: true },
      { key: "deadline", label: "Deadline", type: "text", inQueue: true, inCase: true },
      { key: "bu", label: "Business unit", type: "badge", inQueue: true, inCase: true },
      { key: "system", label: "System of record", type: "text", inQueue: false, inCase: true },
    ],
    dispositions: [
      { key: "act", label: "Open obligation", description: "This is ours. Assign, evidence, track." },
      { key: "monitor", label: "Monitor", description: "Relevant, not yet an owned obligation." },
      { key: "dismiss", label: "Not our citation", description: "Out of perimeter. Keep the audit trail." },
    ],
    cases: [
      {
        id: "reg-cfpb-ai",
        templateId: "regulatory",
        title: "CFPB circular — AI adverse-action notices",
        subject: "CFPB 2026-04 §4.2(b)",
        whyFlagged: "Auto-decision templates in lending do not currently name model version or top factors. Circular is in force.",
        recommendedAction: "Open an obligation on the lending template. Restore disclosure language. Legal review in 48 hours.",
        uncertainty: "Applies cleanly to consumer card. Commercial scoring may be out of scope — confirm with legal before a bank-wide rewrite.",
        evidence: [
          { label: "Feed", detail: "CFPB circular ingested this morning" },
          { label: "OpenPages", detail: "Control C-AA-12 last tested 2025-11, stale" },
          { label: "Asset", detail: "Template AA-AUTO-001 edited 9 days ago" },
        ],
        scores: { harm: 0.9, applicability: 0.82, deadline: 0.88, gap: 0.8 },
        values: {
          citation: "CFPB 2026-04 §4.2(b)",
          owner: "Unassigned",
          deadline: "48 hours (legal)",
          bu: "Consumer lending",
          system: "IBM OpenPages",
        },
        recencyHours: 3,
      },
      {
        id: "reg-occ-mria",
        templateId: "regulatory",
        title: "OCC MRIA — model risk documentation",
        subject: "OCC 2011-12 / MRIA 2026-03",
        whyFlagged: "Exam team asked for challenger-model evidence on the deposit-pricing model. Packet is partial.",
        recommendedAction: "Stand up a response workspace. Pull last validation memo. Do not wait for a perfect pack.",
        uncertainty: "The MRIA language is broader than deposit-pricing. Scope creep is the failure mode.",
        evidence: [
          { label: "Exam", detail: "MRIA dated 16 days ago" },
          { label: "Model inventory", detail: "DP-17 last validated 2024-09" },
          { label: "Gap", detail: "No challenger results attached" },
        ],
        scores: { harm: 0.86, applicability: 0.94, deadline: 0.7, gap: 0.85 },
        values: {
          citation: "OCC 2011-12",
          owner: "Model risk",
          deadline: "Exam follow-up 21 days",
          bu: "Treasury",
          system: "IBM OpenPages",
        },
        recencyHours: 16,
      },
      {
        id: "reg-nydfs",
        templateId: "regulatory",
        title: "NYDFS 500 amendment — MFA on vendors",
        subject: "23 NYCRR 500",
        whyFlagged: "Amendment expands MFA to a class of vendors we treat as low-risk. Inventory is 70% mapped.",
        recommendedAction: "Monitor until the vendor list is complete. Do not open 200 issues. Open one program obligation.",
        uncertainty: "Which vendors are 'class A' is still being argued by InfoSec vs Legal.",
        evidence: [
          { label: "Feed", detail: "Amendment effective in 64 days" },
          { label: "CMDB", detail: "214 vendors, 64 untagged" },
          { label: "OpenPages", detail: "No control owner for vendor MFA" },
        ],
        scores: { harm: 0.68, applicability: 0.6, deadline: 0.55, gap: 0.72 },
        values: {
          citation: "23 NYCRR 500",
          owner: "InfoSec",
          deadline: "64 days",
          bu: "Enterprise",
          system: "IBM OpenPages",
        },
        recencyHours: 28,
      },
      {
        id: "reg-template-drift",
        templateId: "regulatory",
        title: "Approved policy language drifted in production",
        subject: "AA-AUTO-001 vs CFPB clause",
        whyFlagged: "Production template dropped the AI disclosure sentence during a 'plain language' edit.",
        recommendedAction: "Revert to last validated version. Treat as a Sev-1 compliance event, not a copy ticket.",
        uncertainty: "Edit was made by marketing ops with legal 'awareness' — awareness is not approval.",
        evidence: [
          { label: "Diff", detail: "Disclosure clause removed 9 days ago" },
          { label: "Control", detail: "Change-control ticket missing" },
          { label: "Customers", detail: "Template used on 18,400 notices" },
        ],
        scores: { harm: 0.92, applicability: 0.96, deadline: 0.9, gap: 0.66 },
        values: {
          citation: "CFPB 2026-04",
          owner: "Compliance ops",
          deadline: "Immediate",
          bu: "Consumer lending",
          system: "CMS + OpenPages",
        },
        recencyHours: 2,
      },
      {
        id: "reg-bsa-exam",
        templateId: "regulatory",
        title: "BSA exam in 40 days — SAR evidence thin",
        subject: "FinCEN / BSA exam",
        whyFlagged: "Q2 SAR narrative sample failed internal QA on 'complete story' 4 of 12 times.",
        recommendedAction: "Open a targeted QA loop on narratives. Do not relaunch the whole AML stack.",
        uncertainty: "Failure may be documentation quality, not detection quality. Mixing them will panic the exam team.",
        evidence: [
          { label: "QA", detail: "4/12 narratives incomplete" },
          { label: "Exam calendar", detail: "On-site in 40 days" },
          { label: "OpenPages", detail: "Issue I-BSA-09 still open from last exam" },
        ],
        scores: { harm: 0.8, applicability: 0.9, deadline: 0.62, gap: 0.7 },
        values: {
          citation: "31 CFR 1020.320",
          owner: "AML",
          deadline: "40 days",
          bu: "Financial crimes",
          system: "IBM OpenPages",
        },
        recencyHours: 20,
      },
      {
        id: "reg-dora",
        templateId: "regulatory",
        title: "DORA overlap for EU branch",
        subject: "EU DORA · ICT risk",
        whyFlagged: "EU branch is in scope. US parent controls are mapped to NYDFS, not DORA incident clocks.",
        recommendedAction: "Monitor. Build a mapping, do not clone a second GRC tree yet.",
        uncertainty: "Whether the NY booking entity is in scope is still a legal call.",
        evidence: [
          { label: "Perimeter", detail: "EU branch, 40 people" },
          { label: "Clock", detail: "DORA major-incident 4h notify" },
          { label: "OpenPages", detail: "No DORA library loaded" },
        ],
        scores: { harm: 0.5, applicability: 0.42, deadline: 0.4, gap: 0.78 },
        values: {
          citation: "DORA Art. 19",
          owner: "Legal EU",
          deadline: "Mapping Q4",
          bu: "EU branch",
          system: "IBM OpenPages",
        },
        recencyHours: 48,
      },
      {
        id: "reg-orphaned",
        templateId: "regulatory",
        title: "Control owner left — obligation orphaned",
        subject: "UDAAP marketing review",
        whyFlagged: "Owner terminated 19 days ago. OpenPages still lists them. Next test is in 12 days.",
        recommendedAction: "Reassign today. The work is not the issue — the empty chair is.",
        uncertainty: "Backup reviewer exists in a SharePoint list, not in OpenPages.",
        evidence: [
          { label: "HR", detail: "Termination 19 days ago" },
          { label: "OpenPages", detail: "Owner = former employee" },
          { label: "Calendar", detail: "Control test due in 12 days" },
        ],
        scores: { harm: 0.58, applicability: 0.88, deadline: 0.74, gap: 0.5 },
        values: {
          citation: "UDAAP program",
          owner: "Vacant",
          deadline: "12 days",
          bu: "Marketing",
          system: "IBM OpenPages",
        },
        recencyHours: 19,
      },
      {
        id: "reg-state-udaap",
        templateId: "regulatory",
        title: "State UDAAP class language on collections letters",
        subject: "MA 93A / collections",
        whyFlagged: "Plaintiff firm letter cites our 2024 collections template. Letter is not a rule, but the template is still live.",
        recommendedAction: "Monitor the litigation. Spot-check whether the cited sentence is still in production.",
        uncertainty: "This may be a demand letter, not a regulatory action. Treating it as an OCC MRIA would be wrong.",
        evidence: [
          { label: "Legal", detail: "Demand letter received yesterday" },
          { label: "Template", detail: "COL-22 still in production" },
          { label: "OpenPages", detail: "No issue opened yet" },
        ],
        scores: { harm: 0.55, applicability: 0.5, deadline: 0.35, gap: 0.4 },
        values: {
          citation: "MA 93A (alleged)",
          owner: "Litigation",
          deadline: "Response 30 days",
          bu: "Collections",
          system: "Legal hold + OpenPages",
        },
        recencyHours: 22,
      },
    ],
  },
  {
    id: "fraud",
    name: "Fraud analyst",
    operator: "Fraud / financial crimes analyst",
    industry: "Fraud",
    promise:
      "Alerts become a queue the analyst can finish. Severity is harm if true. Priority is whether a human should look now. Uncertainty is a first-class action.",
    adapter: {
      id: "tm",
      name: "Transaction monitoring",
      system: "Actimize / Falcon / in-house TM",
      plug: "Ingest alerts read-only. Analyst dispositions write back as labels for the weekly override review.",
    },
    rankingLabel: "harm × confidence × recency — severity stays independent",
    rankingInputs: [
      { key: "harm", label: "Harm if true", weight: 0.34, hint: "Loss, customer harm, SAR risk." },
      { key: "confidence", label: "Confidence", weight: 0.28, hint: "Low confidence still surfaces if harm is high." },
      { key: "velocity", label: "Velocity / novelty", weight: 0.2, hint: "New pattern vs known customer behavior." },
      { key: "customer", label: "Customer vulnerability", weight: 0.18, hint: "Age, cognitive risk, takeover signs." },
    ],
    fields: [
      { key: "typology", label: "Typology", type: "badge", inQueue: true, inCase: true },
      { key: "amount", label: "Amount", type: "money", inQueue: true, inCase: true },
      { key: "age", label: "Alert age", type: "hours", inQueue: true, inCase: true },
      { key: "channel", label: "Channel", type: "text", inQueue: true, inCase: true },
      { key: "rule", label: "Rule / model", type: "text", inQueue: false, inCase: true },
    ],
    dispositions: [
      { key: "act", label: "Escalate", description: "Investigate / SAR path / hold funds." },
      { key: "monitor", label: "Need more", description: "System is unsure. Ask the human. Do not auto-clear." },
      { key: "dismiss", label: "Clear", description: "False positive. Label it so the model learns." },
    ],
    cases: [
      {
        id: "frd-elder-billpay",
        templateId: "fraud",
        title: "Elder account — new bill-pay payees",
        subject: "Helen Ward, 78 · $14,200",
        whyFlagged: "Three new utility-like payees in 6 days, all LLCs registered this month. Customer has a caregiver on file.",
        recommendedAction: "Need more: call the trusted contact, not the number that initiated the payments.",
        uncertainty: "Could be a real caregiver taking over bills. Could be exploitation. The model cannot tell. That is the point.",
        evidence: [
          { label: "Bill pay", detail: "3 new payees, first-time, $14.2k" },
          { label: "Profile", detail: "Age 78, POA on file 2024" },
          { label: "Device", detail: "Login from caregiver's known device" },
        ],
        scores: { harm: 0.9, confidence: 0.44, velocity: 0.8, customer: 0.95 },
        values: { typology: "Elder / exploitation", amount: 14200, age: 5, channel: "Bill pay", rule: "New payee + age" },
        recencyHours: 5,
      },
      {
        id: "frd-device-ring",
        templateId: "fraud",
        title: "Same device, four new accounts",
        subject: "Device D-8831 · 4 CIFs",
        whyFlagged: "One iOS fingerprint opened four consumer accounts in 31 hours. Two already requested ACH out.",
        recommendedAction: "Escalate. Freeze the four CIFs. This is a ring, not a family.",
        uncertainty: "Low on identity of the operator. High on the pattern. Do not wait for a perfect name.",
        evidence: [
          { label: "Device", detail: "D-8831 shared across 4 CIFs" },
          { label: "KYC", detail: "Synthetic-leaning SSNs, thin files" },
          { label: "Channel", detail: "ACH out requested on 2 of 4" },
        ],
        scores: { harm: 0.84, confidence: 0.88, velocity: 0.96, customer: 0.2 },
        values: { typology: "Synthetic / mule", amount: 6200, age: 3, channel: "Digital", rule: "Device clustering" },
        recencyHours: 3,
      },
      {
        id: "frd-false-pos",
        templateId: "fraud",
        title: "Repeat merchant, similar legal name",
        subject: "Acme Lighting LLC vs Acme Lighting Inc",
        whyFlagged: "Rule fires on near-duplicate merchant strings. This vendor has been paid monthly for 4 years.",
        recommendedAction: "Clear. Add as a known-legitimate pair. This is how analysts lose trust.",
        uncertainty: "Almost none — unless the Inc entity is new. It is not. Confirm once, then stop charging the queue.",
        evidence: [
          { label: "History", detail: "48 prior payments, same ABA" },
          { label: "Rule", detail: "Fuzzy vendor match 0.79" },
          { label: "Analyst", detail: "Cleared 6 times in 2025" },
        ],
        scores: { harm: 0.25, confidence: 0.2, velocity: 0.1, customer: 0.15 },
        values: { typology: "Duplicate vendor", amount: 11840, age: 2, channel: "AP", rule: "Fuzzy vendor" },
        recencyHours: 2,
      },
      {
        id: "frd-ato-wire",
        templateId: "fraud",
        title: "Password reset then wire",
        subject: "Priya Nair · $38,500",
        whyFlagged: "Reset from a new device, then a wire to a first-time beneficiary in 22 minutes.",
        recommendedAction: "Escalate. Hold the wire. Contact on the number of record, not the session number.",
        uncertainty: "Customer could be traveling. The speed is the tell, not the travel.",
        evidence: [
          { label: "Auth", detail: "Reset 22 minutes before wire" },
          { label: "Device", detail: "First seen today, ASN mismatch" },
          { label: "Beneficiary", detail: "New, not in 5-year history" },
        ],
        scores: { harm: 0.86, confidence: 0.8, velocity: 0.9, customer: 0.45 },
        values: { typology: "ATO", amount: 38500, age: 1, channel: "Wire", rule: "Reset + new bene" },
        recencyHours: 1,
      },
      {
        id: "frd-micro-mule",
        templateId: "fraud",
        title: "Micro-deposits then a jump",
        subject: "CIF 440192 · $50 × 8 then $9,400",
        whyFlagged: "Classic pass-through: small inbound, then one large outbound to a new external account.",
        recommendedAction: "Escalate. File the typology. Hold the $9,400 if still pending.",
        uncertainty: "Could be a person aggregating freelance payments. The new outbound ABA is a high-risk bank.",
        evidence: [
          { label: "TM", detail: "8 inbound $50, one outbound $9.4k" },
          { label: "Counterparty", detail: "Receiving bank on mule list" },
          { label: "Age of CIF", detail: "Opened 12 days ago" },
        ],
        scores: { harm: 0.7, confidence: 0.76, velocity: 0.85, customer: 0.3 },
        values: { typology: "Mule", amount: 9400, age: 4, channel: "ACH", rule: "Micro then jump" },
        recencyHours: 4,
      },
      {
        id: "frd-travel-cnp",
        templateId: "fraud",
        title: "CNP spend while customer is traveling",
        subject: "Jonah P. · $2,180 CNP",
        whyFlagged: "Card-not-present in a new MCC while the mobile app shows London — matches the travel notice.",
        recommendedAction: "Clear, or need more only if the MCC is gift cards. Here it is hotels.",
        uncertainty: "Travel notices are not proof, but stacked with app location they are enough.",
        evidence: [
          { label: "Card", detail: "Hotel MCC, 3 charges" },
          { label: "Notice", detail: "Travel UK 8/12–8/20" },
          { label: "App", detail: "London IP, same device" },
        ],
        scores: { harm: 0.3, confidence: 0.35, velocity: 0.4, customer: 0.2 },
        values: { typology: "CNP", amount: 2180, age: 6, channel: "Card", rule: "New geo CNP" },
        recencyHours: 6,
      },
      {
        id: "frd-poa-dispute",
        templateId: "fraud",
        title: "POA and customer both moving money",
        subject: "Arthur Cole · competing instructions",
        whyFlagged: "Durable POA initiated a transfer; the customer called 40 minutes later to cancel it.",
        recommendedAction: "Need more. Freeze both. This is a family/capacity case, not a rule hit.",
        uncertainty: "High. Wrong call either way hurts a person. Escalation is to the elder specialist, not SAR-first.",
        evidence: [
          { label: "POA", detail: "On file, daughter, 2023" },
          { label: "Call", detail: "Customer: 'I did not approve'" },
          { label: "Amount", detail: "$22,000 to daughter's joint" },
        ],
        scores: { harm: 0.88, confidence: 0.4, velocity: 0.55, customer: 0.92 },
        values: { typology: "Elder / POA", amount: 22000, age: 2, channel: "Phone + digital", rule: "Conflicting instruction" },
        recencyHours: 2,
      },
      {
        id: "frd-testing",
        templateId: "fraud",
        title: "Card testing then a jump",
        subject: "PAN ending 4412 · $1.00 × 14",
        whyFlagged: "Fourteen $1 authorizations across random merchants, then a $740 electronics attempt.",
        recommendedAction: "Escalate. Block the PAN. This is testing, not a messy cardholder.",
        uncertainty: "Low. Pattern is clean. Don't spend analyst time re-deriving it.",
        evidence: [
          { label: "Auths", detail: "14 × $1, 11 merchants, 18 min" },
          { label: "Then", detail: "$740 electronics, declined AVS" },
          { label: "3DS", detail: "Not attempted" },
        ],
        scores: { harm: 0.55, confidence: 0.9, velocity: 0.93, customer: 0.1 },
        values: { typology: "Card testing", amount: 740, age: 1, channel: "Card", rule: "Micro-auth burst" },
        recencyHours: 1,
      },
    ],
  },
  {
    id: "engineering",
    name: "Process engineering",
    operator: "Process / reliability engineer",
    industry: "Operations",
    promise:
      "Deviations, bottlenecks, and change control stop living in five systems. The engineer gets a ranked queue: intervene, watch, or in-control.",
    adapter: {
      id: "mes",
      name: "MES + historian + LIMS + QMS",
      system: "OSIsoft PI / MES / TrackWise",
      plug: "Tags, batches, and CAPAs map into one case. Writes go back as dispositions, not as a new system of record.",
    },
    rankingLabel: "safety × production loss × time-to-constraint × confidence",
    rankingInputs: [
      { key: "safety", label: "Safety / quality", weight: 0.34, hint: "Harm to people, product, or license." },
      { key: "loss", label: "Production loss", weight: 0.26, hint: "Throughput, yield, or delay." },
      { key: "constraint", label: "Time to constraint", weight: 0.22, hint: "How soon the plant feels it." },
      { key: "confidence", label: "Signal confidence", weight: 0.18, hint: "Sensor / lab / operator agreement." },
    ],
    fields: [
      { key: "asset", label: "Asset / unit", type: "text", inQueue: true, inCase: true },
      { key: "loss", label: "Est. loss", type: "money", inQueue: true, inCase: true },
      { key: "window", label: "Window", type: "hours", inQueue: true, inCase: true },
      { key: "type", label: "Type", type: "badge", inQueue: true, inCase: true },
      { key: "source", label: "Source", type: "text", inQueue: false, inCase: true },
    ],
    dispositions: [
      { key: "act", label: "Intervene", description: "Stop, adjust, or open MOC/CAPA now." },
      { key: "monitor", label: "Watch", description: "Real signal. Not yet past the line." },
      { key: "dismiss", label: "In control", description: "Noise or already inside the spec. Label it." },
    ],
    cases: [
      {
        id: "eng-flooding",
        templateId: "engineering",
        title: "Distillation column approaching flood",
        subject: "T-410 · C3 splitter",
        whyFlagged: "Differential pressure up 38% in 6 hours. Reflux was raised after a composition giveaway. Flood line is close.",
        recommendedAction: "Intervene: cut reflux 8%, hold feed. Do not wait for the high-DP trip.",
        uncertainty: "DP tap may be partially plugged. Board operator thinks so. Lab composition disagrees — lab is late.",
        evidence: [
          { label: "PI", detail: "DP 38% above baseline, 6h" },
          { label: "Lab", detail: "C3 in bottoms still high" },
          { label: "Board", detail: "Operator note: tap suspect" },
        ],
        scores: { safety: 0.78, loss: 0.82, constraint: 0.9, confidence: 0.62 },
        values: { asset: "T-410", loss: 186000, window: 3, type: "Bottleneck", source: "PI + board" },
        recencyHours: 2,
      },
      {
        id: "eng-spc",
        templateId: "engineering",
        title: "SPC shift on impurity",
        subject: "LIMS · spec impurity B",
        whyFlagged: "Eight points on the same side of the mean. Still in spec. This is the Western Electric alarm, not a batch fail.",
        recommendedAction: "Watch. Increase sample frequency. Do not scrap. Find the shift cause on the day shift.",
        uncertainty: "Method change in LIMS yesterday. Could be analytical, not process.",
        evidence: [
          { label: "LIMS", detail: "8 consecutive points above mean" },
          { label: "Spec", detail: "Still 62% of limit" },
          { label: "Method", detail: "GC method v1.4 deployed yesterday" },
        ],
        scores: { safety: 0.55, loss: 0.3, constraint: 0.4, confidence: 0.5 },
        values: { asset: "Finishing", loss: 24000, window: 24, type: "Quality", source: "LIMS" },
        recencyHours: 8,
      },
      {
        id: "eng-moc",
        templateId: "engineering",
        title: "MOC for catalyst change not closed",
        subject: "MOC-2026-118",
        whyFlagged: "Catalyst swap ran 4 days ago. MOC still 'in review.' PSSR checklist is unsigned.",
        recommendedAction: "Intervene on the paperwork, not the unit — unless PSSR items are actually open. Walk the unit.",
        uncertainty: "Ops says the walkthrough happened. QMS does not. That gap is the incident report later.",
        evidence: [
          { label: "QMS", detail: "MOC open, PSSR unsigned" },
          { label: "Ops", detail: "Shift log: walkthrough complete" },
          { label: "Unit", detail: "Rates at 94% of new design" },
        ],
        scores: { safety: 0.7, loss: 0.2, constraint: 0.55, confidence: 0.75 },
        values: { asset: "R-200", loss: 0, window: 12, type: "Change control", source: "TrackWise" },
        recencyHours: 10,
      },
      {
        id: "eng-capa",
        templateId: "engineering",
        title: "CAPA overdue from April leak",
        subject: "CAPA-441 · flange leak",
        whyFlagged: "Action 3 of 5 is 16 days late. It was the training item. The hardware is done.",
        recommendedAction: "Watch the hardware. Intervene on the overdue training — that is what the auditor will ask.",
        uncertainty: "Training LMS may have completed it under a different course code.",
        evidence: [
          { label: "QMS", detail: "CAPA-441 action 3 overdue 16d" },
          { label: "Maintenance", detail: "Gasket + torque complete" },
          { label: "LMS", detail: "No completion on original module id" },
        ],
        scores: { safety: 0.48, loss: 0.1, constraint: 0.35, confidence: 0.7 },
        values: { asset: "P-118", loss: 0, window: 48, type: "CAPA", source: "TrackWise" },
        recencyHours: 16,
      },
      {
        id: "eng-fouling",
        templateId: "engineering",
        title: "Heat exchanger fouling trend",
        subject: "E-330 · duty down 11%",
        whyFlagged: "UA trending down 11% over 19 days. Turnaround is in 7 weeks. If we wait, the constraint moves to this exchanger.",
        recommendedAction: "Watch this week, schedule a clean in the next opportunity window. Don't emergency-open.",
        uncertainty: "Process side vs utility side is not isolated. One more test with inlet temps will tell.",
        evidence: [
          { label: "PI", detail: "Duty −11% vs baseline" },
          { label: "Plan", detail: "TA in 7 weeks" },
          { label: "Energy", detail: "Steam up 6% to compensate" },
        ],
        scores: { safety: 0.25, loss: 0.58, constraint: 0.5, confidence: 0.72 },
        values: { asset: "E-330", loss: 42000, window: 168, type: "Reliability", source: "PI" },
        recencyHours: 14,
      },
      {
        id: "eng-genealogy",
        templateId: "engineering",
        title: "Batch genealogy mismatch",
        subject: "Batch 8H-221",
        whyFlagged: "MES says drum 14 came from lot A. LIMS COA is lot B. Warehouse scan is lot B.",
        recommendedAction: "Intervene: hold the batch. Do not ship on a majority vote.",
        uncertainty: "Could be a scan error. Could be a mix. Quality does not get to be optimistic here.",
        evidence: [
          { label: "MES", detail: "Drum 14 → lot A" },
          { label: "LIMS", detail: "COA lot B" },
          { label: "WMS", detail: "Scan lot B" },
        ],
        scores: { safety: 0.88, loss: 0.64, constraint: 0.8, confidence: 0.6 },
        values: { asset: "Packaging", loss: 96000, window: 6, type: "Quality hold", source: "MES + LIMS" },
        recencyHours: 3,
      },
      {
        id: "eng-alarms",
        templateId: "engineering",
        title: "Alarm flood on DCS",
        subject: "Board 2 · 140 alarms / 10 min",
        whyFlagged: "ISA 18.2 rate is blown. Operators are silencing. The plant is not necessarily unsafe — the interface is.",
        recommendedAction: "Intervene on alarm configuration for the bad actor tags. Don't add another banner.",
        uncertainty: "A real process excursion can hide in a flood. Check the 5 high-priority tags first.",
        evidence: [
          { label: "DCS", detail: "140 alarms / 10 min" },
          { label: "Bad actors", detail: "3 tags = 61% of count" },
          { label: "Priority", detail: "12 priority-1, none standing" },
        ],
        scores: { safety: 0.6, loss: 0.35, constraint: 0.7, confidence: 0.85 },
        values: { asset: "Board 2", loss: 0, window: 8, type: "Alarm", source: "DCS" },
        recencyHours: 1,
      },
      {
        id: "eng-steam",
        templateId: "engineering",
        title: "Steam header at constraint",
        subject: "Utilities · 600# header",
        whyFlagged: "Header pressure sagging to 545 psig on a 600# system while two units raise rates. This is a plant-wide bottleneck, not a local one.",
        recommendedAction: "Watch 2 hours. If it kisses 540, cut the lowest-margin rate. Don't let both units 'optimize' locally.",
        uncertainty: "Boiler 3 is in a runback. If it recovers, this disappears. If it doesn't, this is tonight's call.",
        evidence: [
          { label: "PI", detail: "600# header 545 psig" },
          { label: "Boiler 3", detail: "Runback, 72% load" },
          { label: "Units", detail: "T-410 and R-200 both raising" },
        ],
        scores: { safety: 0.52, loss: 0.77, constraint: 0.88, confidence: 0.8 },
        values: { asset: "Utilities", loss: 210000, window: 2, type: "Bottleneck", source: "PI" },
        recencyHours: 1,
      },
    ],
  },
];

export const TEMPLATE_MAP = Object.fromEntries(TEMPLATES.map((t) => [t.id, t])) as Record<
  ProcessTemplate["id"],
  ProcessTemplate
>;
